config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  get '/welcome/me'
  resources :welcome do
    get :search, :on => :collection
  end
  resources :users
  resources :restaurants do
    resources :reservations do
      get :availability_check, :on => :collection
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reservations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = current_user
    @reservations = current_user.reservations
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container text-center">
  <div class="content">
    <h1><strong>Welcome <%= @current_user.first_name %>!!</strong></h1>
    <h2>Your reservations:</h2>
    <table class="table table-striped table-hover">
      <tr>
        <th class="text_center">Restaurant</th>
        <th class="text_center">Phone Number</th>
        <th class="text_center">Date</th>
        <th class="text_center">Time</th>
        <th class="text_center">Party Number</th>
        <th class="text_center">Cancel</th>
      </tr>
      <tbody>
        <% if @reservations.length > 0%>
          <% @reservations.each do |reservation| %>
            <tr class='info'>
              <td> <%= reservation.restaurant.name %> </td>
              <td> <%= number_to_phone(reservation.restaurant.phone_number, area_code: true) %> </td>
              <td> <%= reservation.start_time.strftime("%A %m/%d/%Y")  %> </td>
              <td> <%= reservation.start_time.strftime("%I:%M %p")  %> </td>
              <td> <%= reservation.party_number %> </td>
              <td><%= link_to 'Cancel', restaurant_reservation_path(reservation.restaurant, reservation), :method => :delete, :class => "btn btn-danger"%></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>